<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Abp" Version="10.5.*" />
    <PackageReference Include="Abp.TestBase" Version="10.5.*" />
    <PackageReference Include="Castle.Windsor.MsDependencyInjection" Version="6.0.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.*" />
    <PackageReference Include="NSubstitute" Version="5.3.*" />
    <PackageReference Include="Shouldly" Version="4.3.*" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CommunityAbp.AspNetZero.DistributedEventBus.AzureServiceBus\CommunityAbp.AspNetZero.DistributedEventBus.AzureServiceBus.csproj" />
    <ProjectReference Include="..\..\src\CommunityAbp.AspNetZero.DistributedEventBus.EntityFrameworkCore\CommunityAbp.AspNetZero.DistributedEventBus.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
