// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CommunityAbp.AspNetZero.DistributedEventBus.EntityFrameworkCore.EntityFrameworkCore;

#nullable disable

namespace CommunityAbp.AspNetZero.DistributedEventBus.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DistributedEventBusDbContext))]
    partial class DistributedEventBusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
            modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("CommunityAbp.AspNetZero.DistributedEventBus.EntityFrameworkCore.EventInboxOutbox.InboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<byte[]>("EventData")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<string>("EventName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Error")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MessageId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("ProcessedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("ReceivedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("RetryCount")
                    .HasColumnType("int");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("nvarchar(40)");

                b.HasKey("Id");

                b.HasIndex("MessageId")
                    .IsUnique();

                b.ToTable("InboxMessages");
            });

            modelBuilder.Entity("CommunityAbp.AspNetZero.DistributedEventBus.EntityFrameworkCore.EventInboxOutbox.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<byte[]>("EventData")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<string>("EventName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Error")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RetryCount")
                    .HasColumnType("int");

                b.Property<DateTime?>("SentAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("nvarchar(40)");

                b.HasKey("Id");

                b.ToTable("OutboxMessages");
            });
#pragma warning restore 612, 618
        }
    }
}
